### PR TITLE
fix components order issue

### PR DESCRIPTION
**Pull request by hhelibeb**
There is a side effect of the conversion: The order of keys is always sorted after converting,
image

Reason: /UI2/CL_JSON->GENERATE_INT use a SORTED table LT_FILEDS to process data.

In order to keep ABAP components order same as the original order of JSON data, the data type of LT_FILEDS should be HASHED table.

ZUI2_JSON is a class copied from /UI2/CL_JSON. And the LT_FILEDS in ZUI2_JSON is hashed table, so it can keep original order when converting. All occurrences of /UI2/CL_JSON in report ZJSON2ABAPTYPE is replaced by ZUI2_JSON now,
image

It is important to ensure that ZUI2_JSON has the same behavior in other respects.  The local test classes copied form /UI2/CL_JSON guarantee that ZUI2_JSON works as good as /UI2/CL_JSON,
image

ZUI2_DATA_ACCESS is another class introduced in this commit, it is necessary for unit tests.

### CODE REVIEW

**Comment by fidley** [comment]
Thanks @hhelibeb . I will firslty check it with my own examples to see if this does not crash the program. Will try to do this still today or through the weekend. 

Thank you very much for contribution, do you have any twitter handle?

**Comment by hhelibeb** [comment]
@fidley No, I would like to use twitter to get information. But seems twitter blocks China mainland phone number since several years. So I can't use it anymore 😆 
As a young developer, I benifit from open source a lot. I'm glad to work on open source projects and hope to be a good developer, just like you, like larshp..

**Comment by fidley** [comment]
Thanks once again for this. It's a pity that you cannot use twitter. Is community.sap.com allowed in China? Do you have user there? I'd like to shout out about your contribution :)

**Comment by hhelibeb** [comment]
@fidley Thanks, that is very good. My sap account is: [https://people.sap.com/marspark](https://people.sap.com/marspark)

**Pull request merged**
